<a href="https://colab.research.google.com/github/TDKhoa2712/SGU_PTDL_2025/blob/main/slide_03_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tổng hợp Code Python Data Analysis và Visualization

##1. NUMPY - Numerical Python

###1.1. So sánh List thông thường vs NumPy Array

In [5]:
#Python Data Structure
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

#List[]
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [1]:
# Sử dụng list thông thường
v = list(range(1, 6))
print(v)          # Kết quả: [1, 2, 3, 4, 5]
print(2 * v)      # Kết quả: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] (nhân đôi danh sách)

# Sử dụng NumPy array
import numpy as np
v = np.arange(1, 6)
print(v)          # Kết quả: [1 2 3 4 5]
print(2 * v)      # Kết quả: [2 4 6 8 10] (nhân từng phần tử với 2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1 2 3 4 5]
[ 2  4  6  8 10]


#####Giải thích:

* List thông thường: 2 * v tạo ra một list mới bằng cách lặp lại list gốc 2 lần
* NumPy array: 2 * v thực hiện phép nhân vectorized, nhân từng phần tử với 2

###1.2. Tạo và thao tác với NumPy Array

In [2]:
import numpy as np

# Tạo array từ list
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)
c = a * b
print(c)          # Kết quả: [4 10 18] (nhân từng cặp phần tử tương ứng)

[1 2 3]
[4 5 6]
[ 4 10 18]


####Các phương thức tạo đặc biệt

In [1]:
import numpy as np

#Khởi tạo một ma trận không
a = np.zeros((2,2))
print(a)

#Khởi tạo một array toàn số 1
b = np.ones((1,2))
print(b)

#Khởi tạo một ma trận với giá trị được chỉ định
c = np.full((2,2), 7)
print(c)

#Khởi tạo một ma trận đơn vị
d = np.eye(2)
print(d)

#Khởi tạo một ma trận với các giá trị ngẫu nhiên
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.64239653 0.31008764]
 [0.70656569 0.33805608]]


###1.3. Array đa chiều và thuộc tính

In [ ]:
import numpy as np

# Tạo array 2D với reshape
a = np.arange(15).reshape(3, 5)
print(a)
# Kết quả:
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

print(a.shape)      # Kết quả: (3, 5) - 3 hàng, 5 cột
print(a.ndim)       # Kết quả: 2 - 2 chiều
print(a.dtype.name) # Kết quả: 'int64' - kiểu dữ liệu